# Generated by Django 4.2.13 on 2024-05-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
