# Generated by Django 4.2.13 on 2024-05-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('number_of_persons', models.PositiveIntegerField(default=1)),
                ('booking_date', models.DateField(auto_now=True)),
                ('booking_time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
