# Generated by Django 4.2.13 on 2024-05-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='booking_time',
            field=models.TimeField(),
        ),
    ]
