# Generated by Django 4.2.13 on 2024-05-10 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_book_booking_date_alter_book_booking_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['booking_date']},
        ),
    ]
