# Generated by Django 4.2.13 on 2024-06-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
